---
title: "Case Study 1 - ETL"
author: "Nikhil Gupta"
date: "`r Sys.time()`"
always_allow_html: yes
output:
  github_document:
    toc: true
    toc_depth: 6
  html_document:
    toc: true
    toc_float: true
    toc_depth: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
version
```

Section 2.7 from text (Chapter 2)

```{r}
# install.packages("XML", type = "binary")
```

```{r}
library(XML)
ubase = "http://www.cherryblossom.org/"
url = paste(ubase, "results/2012/2012cucb10m-m.htm", sep = "")
doc = htmlParse(url)
```

```{r}
preNode = getNodeSet(doc, "//pre")
txt = xmlValue(preNode[[1]])
nchar(txt)
```

```{r}
substr(txt, 1, 50)
```

```{r}
substr(txt, nchar(txt) - 50, nchar(txt))
```


```{r}
els = strsplit(txt, "\\r\\n")[[1]]
length(els)
```

```{r}
els[1:3]
```

```{r}
els[ length(els) ]
```

```{r}
# Retrieve data from web site, find preformatted text,
# return as a character vector.
extractResTable = function(url){
  doc = htmlParse(url)
  preNode = getNodeSet(doc, "//pre")
  txt = xmlValue(preNode[[1]])
  els = strsplit(txt, "\r\n")[[1]]
  return(els)
}
```

```{r}
m2012 = extractResTable(url)
identical(m2012, els)
```

```{r}
ubase = "http://www.cherryblossom.org/"
urls = paste(ubase, "results/", 1999:2012, "/", 1999:2012, "cucb10m-m.htm", sep = "")
urls
```


```{r}
# # This is for debugging the errors
# options(error = recover)
# menTables = lapply(urls, extractResTable)
```

```{r}
# Some links have been changed from book
menURLs = c(
  "results/1999/cb99m.html", "results/2000/cb003m.htm", "results/2001/oof_m.html",
  "results/2002/oofm.htm", "results/2003/CB03-M.HTM",
  "results/2004/men.htm", "results/2005/CB05-M.htm",
  "results/2006/men.htm", "results/2007/men.htm",
  "results/2008/men.htm", "results/2009/09cucb-M.htm",
  "results/2010/2010cucb10m-m.htm",
  "results/2011/2011cucb10m-m.htm",
  "results/2012/2012cucb10m-m.htm"
)
urls = paste(ubase, menURLs, sep = "")
urls
```

```{r}
options(error = recover)
menTables = lapply(urls, extractResTable)
names(menTables) = 1999:2012
```

```{r}
sapply(menTables, length)
```


```{r}
# Retrieve data from web site, find preformatted text,
# return as a character vector.
extractResTable = function(url, year = 1999){
  doc = htmlParse(url)
  if (year == 2000){
    # Get text from 4th font element
    # File is ill-formed so <pre> search doesn’t work.
    ff = getNodeSet(doc, "//font")
    txt = xmlValue(ff[[4]])
  }
  else if(year == 2009){
    # Special handling for 2009 format
    preNode = getNodeSet(doc, "//pre")
  }
  else{
    preNode = getNodeSet(doc, "//pre")
    txt = xmlValue(preNode[[1]])
  }
  
  if (year == 1999){
    els = strsplit(txt, "\n")[[1]]  # [-1] # No need to remove the 1st line
  }
  else if (year == 2009){
    els = c()
    for(i in 1:length(preNode)){  # 7:6657 # No need to remove the 1st few and last couple of lines for now
      # Remove &nbsp from text
      els = c(els, gsub("Â", "", xmlValue(preNode[[i]]), fixed =TRUE))
    }
  }
  else{
    els = strsplit(txt, "\r\n")[[1]]
  }
  return(els)
}
```


```{r}
# url_temp = "http://www.cherryblossom.org/results/1999/cb99m.html"
# doc = htmlParse(url_temp)
# preNode = getNodeSet(doc, "//pre")
```

```{r}
# txt = xmlValue(preNode[[1]])
# strsplit(txt, "\n")[[1]]
```

```{r}
# a = extractResTable(urls[1], year=1999)
# str(a)
```

```{r}
# a = extractResTable(urls[2], year=2000)
# str(a)
```

```{r}
years = 1999:2012
menTables = mapply(extractResTable, url = urls, year = years)
```


```{r}
names(menTables) = years
sapply(menTables, length)
```

```{r}
menTables[['2009']][1:10]
```

```{r}
saveRDS(menTables, file = "../../data/CBMenTextTables.rds")
```





```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

