---
title: "MaxCs2"
author: "Max Moro"
date: "9/9/2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(hms)
library(rvest)
library(lubridate)
library(foreach)
library(stringr)
library(iterators)

years = c(1999:2012)
division = 'Overall+Women' #'Overall+Men"
section = '10M' 

```

# Functions

```{r}
getLink = function(year,division,section,page=1){
  #this function just create the link with the query parameters 
  paste0( 'http://www.cballtimeresults.org/performances'
          ,'?utf8=%E2%9C%93&section=',section
          ,'&year=',year,'&division=',division,'&page=', page)
}

getTable = function(year,division,section,page){
  #this function reads the page and convert to a dataframe
  
  #get the link to the apge
  link=getLink(year,division,section,page=page)
  
  #read the page, and grab to 'table' tag
  t=read_html(link)  %>% 
    html_nodes("table")  %>% 
    html_table(fill=TRUE) 
  
  #get the table and add metadat for the query paramters
  out = t[[1]] %>%
    mutate(year=year, divisionTitle=division, section=section, page=page, link=link)
}

getAllTables  = function(years,division,section,useCachedWebData = FALSE){
  library(progress)
  library(doParallel)
  library(doSNOW)
  
  if(!useCachedWebData) {
    #init parallel process with max number of cores
    cl <- makeCluster(detectCores())
    doSNOW::registerDoSNOW(cl)
    
    #progress bar for the parallel loop
    pb <- progress::progress_bar$new(total = length(years),format='[:bar] :percent :eta')
    progress <- function(n) pb$tick()
    
    #start a parellel loop per each year
    dataRaw=NULL
    dataRaw = foreach(y=years
                      ,.combine=rbind,.export=c('getTable','getLink')
                      ,.options.snow = list(progress=progress)) %dopar%
      {
        library(foreach)
        library(rvest)
        library(dplyr)
        isCompleted=FALSE
        
        #loop to parse all pages
        dataRaw=foreach(p=c(1:1000),.combine=rbind) %do% 
          if(!isCompleted) {
            message('getting year:',y, ' page:',p,appendLF = F)
            #get the table of the current page
            table = getTable(year=y
                             ,division=division
                             ,section=section
                             ,page=p)
            message(' rows:',nrow(table))
            isCompleted = nrow(table)==0 #if there is record, we are at the last page, no need to read further
            return(table)
          }
        return(dataRaw)
      }
    stopCluster(cl)
    #save the raw data
    saveRDS(dataRaw,file='../../data/dataRaw.rds')
  } else {
    #read teh raw data
    dataRaw= readRDS(file='../../data/dataRaw.rds')
  }
  return(dataRaw)
}

transformAllTables =function(dataRaw){
  #fix columns and content
  data = dataRaw %>%
    separate(col='Name',c('Name','Gender'),sep='[\\(\\)]'
             ,extra='drop',remove=TRUE) %>% #split name cols to name and gender
    separate(col='PiS/TiS',c('PiS','TiS'),sep='\\/'
             ,extra='drop',remove=TRUE) %>% #split PiS/TiS cols
    separate(col='PiD/TiD',c('PiD','TiD'),sep='\\/'
             ,extra='drop',remove=TRUE) %>% #split PiD/TiD cols
    separate(col='Hometown',c('Hometown','HomeState')
             ,sep=',',extra='merge',remove=TRUE,fill='right') %>% #split Hometown and state
    mutate(Hometown=trimws(Hometown) #remove trim space
           ,Hometown =  ifelse(Hometown %in% c('NR',''),NA, Hometown) #convert NR and '' to NA
           ,HomeState = trimws(HomeState) #remove trim space
           ,HomeState = ifelse(HomeState %in% c('NR',''),NA, HomeState) #convert NR and '' to NA
           ,HomeState = trimws(toupper(ifelse(is.na(HomeState),Hometown,HomeState))) #if state is null, it is saved in the hometown
           ,HomeCountry = ifelse(HomeState %in% toupper(c('DC',state.abb)), 'USA',HomeState) #check if is a USA state
           ,Hometown = ifelse(toupper(Hometown) == HomeState,NA,Hometown) #set town to NA if is the same of state
           ,HomeState = ifelse(HomeState == HomeCountry,NA,HomeState) #set State  to NA if is = to coutnry
           ,Race = trimws(substr(Race,5,100)) #gram race type race cols
           ,Time = parse_date_time(gsub('\\*\\*','',Time)
                                   , orders = c("HMS", "MS")) #convert time col to time format
           ,TimeMins = second(Time)/60 + minute(Time)  + hour(Time)*60  #convert time to minus
           ,Pace = parse_date_time(gsub('\\*\\*','',Pace)
                                   , orders = c("HMS", "MS"))  #convert pace col to time format
           ,PaceMins = second(Pace)/60 + minute(Pace)  + hour(Pace)*60  #convert pace time to mins
           ,Age = as.numeric(Age) #convert age to numeric
           ,PiS = as.numeric(PiS) #convert PiS to numeric
           ,TiS = as.numeric(TiS) #convert TiS to numeric
           ,PiD = as.numeric(PiD) #convert PiD to numeric
           ,TiD = as.numeric(TiD) #convert TiD to numeric
    ) 
    
  #fixing missing home state (the state is save as town)
  return(data )
}
```

# Run ETL

```{r}
dataRaw=getAllTables(years=years,division = division,section=section,useCachedWebData = TRUE)
data=transformAllTables(dataRaw=dataRaw)
if(F) saveRDS(data,file='../../data/data.rds')
head(data)
data %>%
  group_by(year) %>%
  summarize(rows = n())
```
# Check Data Structurs
```{r}
  summary(data)
```

