---
title: "Max_CS1"
author: "Max Moro"
date: "8/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
dataLoc = '../../data/'
library(tidyverse)
library(ggplot2)
```

# Read Data
```{r}
offline= readRDS(file.path(dataLoc,'offline.rds'))
subMacs = names(sort(table(offline$mac), decreasing = TRUE))[1:7]

online= readRDS(file.path(dataLoc,'online.rds'))

```

# Exploring

## Signal vs. Angle

```{r}
library(ggplot2)

p=ggplot(data=filter(offline, mac != "00:0f:a3:39:dd:cd")
         ,aes(y=signal,x=factor(angle))) +
  ggplot2::geom_violin()+
  ggplot2::facet_wrap(vars(mac))
p

```
## Density Signal by MAC Angle

```{r fig.height=10, fig.width=10}
p=ggplot(data=filter(offline, mac != "00:0f:a3:39:dd:cd")
         ,aes(x=signal) 
         ) +
  ggplot2::geom_density()+
  ggplot2::facet_wrap(vars(mac
                           ,paste0('Angle:',angle)))
p


```

## SD Signal Strenth by Mean 

```{r}
byLocAngleAP = with(offline,
                    by(offline, list(posXY, angle, mac),
                       function(x) x))

signalSummary =
  lapply(byLocAngleAP,
         function(oneLoc) {
           ans = oneLoc[1, ]
           ans$medSignal = median(oneLoc$signal)
           ans$avgSignal = mean(oneLoc$signal)
           ans$num = length(oneLoc$signal)
           ans$sdSignal = sd(oneLoc$signal)
           ans$iqrSignal = IQR(oneLoc$signal)
           ans
         })
offlineSummary = do.call("rbind", signalSummary)

offlineSummary[1:10]
```


```{r}
breaks = seq(-90, -30, by = 5)
p=ggplot(data=filter(offlineSummary, mac != "00:0f:a3:39:dd:cd")
         ,aes(y=sdSignal,x=cut(avgSignal,breaks=breaks)) 
         ) +
  ggplot2::geom_boxplot()

  
p
```
## Avg - Med Signal vs obs

```{r}

with(offlineSummary,
     smoothScatter((avgSignal - medSignal) ~ num,
                   xlab = "Number of Observations",
                   ylab = "mean - median"))
abline(h = 0, col = "#984ea3", lwd = 2)

lo.obj =
  with(offlineSummary,
       loess(diff ~ num,
             data = data.frame(diff = (avgSignal - medSignal),
                               num = num)))

lo.obj.pr = predict(lo.obj, newdata = data.frame(num = (70:120)))
lines(x = 70:120, y = lo.obj.pr, col = "#4daf4a", lwd = 2)
```

## Signal and Distnace

```{r fig.height=8, fig.width=8}

library(fields)
surfaceSS = function(data, sel_mac, sel_angle = 45) {
 
   oneAPAngle = filter(data, mac ==sel_mac & angle == sel_angle)
  x=data.frame(as.numeric(oneAPAngle$posX),as.numeric(oneAPAngle$posY))
  y=oneAPAngle$avgSignal
  smoothSS = Tps(x,y)
  vizSmooth = predictSurface(smoothSS)
  plot.surface(vizSmooth, type = "C")
  points(oneAPAngle$posX, oneAPAngle$posY, pch=19, cex = 0.5)
}

parCur = par(mfrow = c(2,2), mar = rep(1.5, 4))

mapply(surfaceSS, 
       sel_mac = subMacs[ rep(c(5, 1), each = 2) ], 
       sel_angle = rep(c(0, 135), 2),
       data = list(data = offlineSummary))

par(parCur)

```

