---
title: "Max_CS7"
author: "Nikhil, Moro, Bhuvana"
date: "11/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(tidyverse)
library(qs)
library(cowplot)
library(ggrepel)
library(scales)
```

# Loading Data

```{r}
folder = 'C:/max/OneDriveSMU/OneDrive - Southern Methodist University/2020-08 QTW/CS7'
if(F){
  dataRaw = read.csv(file.path(folder,'final_project.csv'))
  saveRDS(data_raw,file.path(folder,'final_project.rds'))
}  else{
  dataRaw = readRDS(file.path(folder,'final_project.rds'))
}

dataRaw = dataRaw %>%
  mutate(y = ifelse(y==1,'y','n')
         ,x37 = as.numeric(gsub('[$,]','',x37))
         ,x32 = as.numeric(gsub('[%,]','',x32))/100
  )
  
```


# EDA

## numeric Columns

```{r fig.height=20, fig.width=10}
numCols = colnames(dataRaw)[which(lapply(dataRaw,class)=='numeric')]
```

### Checking Missing Values

```{r}
NAs = sapply(numCols,function(col){sum(is.na(dataRaw[[col]]))})
print(NAs)
NAsRows = NAsRows = unique(unlist(lapply(numCols,function(col){which(is.na(dataRaw[[col]]))})))
print(length(NAsRows))

```
### Variables Distribution

```{r fig.height=20, fig.width=10}


p = lapply(numCols
           ,function(col){
             dt=dataRaw[-NAsRows,]
             annotation = data.frame(x = min(dt[[col]]),y=0
                                     ,label = paste0('std:',scales::comma(sd(dt[[col]]),accuracy=0.001)
                                                     ,'\nmean:',scales::comma(mean(dt[[col]]),accuracy=0.001)
                                     ))
             ggplot(data=dt,aes_string(x=col)) +
               ggplot2::geom_density() +
               geom_text(data=annotation,aes(x=x,y=y,label=label),color='blue',hjust=0,size=3,vjust=-1)
           }
           
)
cowplot::plot_grid(plotlist = p,nrow = ceiling(length(numCols)/5),ncol =5 , label_size=5)

```
### Correlation
```{r fig.height=10, fig.width=10}
dataCor = cor(dataRaw[-NAsRows,numCols])
dataCorDF = as.data.frame(as.table(dataCor))

highCorr = filter(dataCorDF,abs(Freq)>0.9, Var1 != Var2) %>% arrange(-Freq)
print(highCorr)


corrplot::corrplot(dataCor
                   ,method='square'
                   ,type='full'
                   ,order='AOE')


```


### Correlation with Target

```{r fig.height=20, fig.width=10}
summ_fun <- function(x){
  return(rbind(data.frame(y=min(x),label = paste0('avg: ',scales::comma(mean(x),accuracy=0.01)))))
}

p = lapply(numCols 
           ,function(col){
             dt=dataRaw[-NAsRows,]
             dt$target = as.factor(dt$y)
             ggplot(data=dt,aes_string(y=col,group='target',x='target',fill='target')) +
               ggplot2::geom_violin(color="#88888820")+
               ggplot2::geom_boxplot(outlier.color = NA,width=0.2)  +
               ggplot2::stat_summary( fun.data=summ_fun,geom='text',color='blue',size=3#,hjust=0
                                      #,position=ggplot2::position_nudge(x=0.2)
               ) +
               
               scale_fill_brewer(palette ='Blues') +
               scale_color_brewer(palette ='Blues')  +
               ggplot2::theme(text = element_text(size=10)
                              ,axis.text.x = element_text(angle=90,size=10)
                              ,legend.position = "none"
               )
           }
           
)
cowplot::plot_grid(plotlist = p,nrow = ceiling(length(numCols)/5),ncol =5 , label_size=2)

```

## Qualitative Columns

```{r fig.height=20, fig.width=10}

textCols = colnames(dataRaw)[which(lapply(dataRaw,class)!='numeric')]
```

### Checking Missing Values

```{r}
NAs = sapply(textCols,function(col){sum(is.na(dataRaw[[col]]))})
print(NAs)
NAsRows = NAsRows = unique(unlist(lapply(textCols,function(col){which(is.na(dataRaw[[col]]))})))
print(length(NAsRows))

```
### Count of Records
```{r}
uniqueCounts = sapply(textCols,function(x)length(unique(dataRaw[[x]])))
uniqueCounts
#remove x37 as too many details

```


### Variables Distribution

```{r fig.height=10, fig.width=10}


p = lapply(textCols
           ,function(col){
             dt=dataRaw
             dt[[col]]=forcats::fct_reorder(factor(dataRaw[[col]]),.x = factor(dataRaw[[col]]), .fun = length)
             ggplot(data=dt,aes_string(x=col
                                       ,fill=col)) +
               ggplot2::geom_bar() +
               geom_text(stat='count', aes(
                 #label=comma(..count..,accuracy=1)
                 label=paste0(comma(..count..,accuracy=1),'\n(',percent(..count../sum(..count..),accuracy=1),')')
                 ), size=3,vjust=1 ) +
               #scale_fill_brewer(palette ='Blues') +
               ggplot2::theme(text = element_text(size=10)
                              ,axis.text.x = element_text(angle=90,size=10)
                              ,legend.position = "none")
           }
           
)
cowplot::plot_grid(plotlist = p,nrow = ceiling(length(textCols)/2),ncol =2 , label_size=5)

```



### Correlation with Target

```{r fig.height=10, fig.width=10}

p = lapply(textCols[textCols!='y']
           ,function(col){
             dt=dataRaw %>%
               mutate(col=.[[col]]) %>%
               group_by(col,y) %>%
               summarize(count = n()) %>%
               group_by(col) %>%
               mutate(label=paste0(comma(count,accuracy=1),' (', percent(count/sum(count)),')')
                      ,tot= sum(count)) %>%
               ungroup() %>%
               mutate(col=forcats::fct_reorder(factor(col),tot))
            
            Ncol = '#2b8cbe'
            Ycol = '#a6bddb'
            ynote = levels(dt$col)[ceiling(length(levels(dt$col))/2)]
             note=rbind(data.frame(y=ynote,x=max(filter(dt,y=='y')$count)
                                   ,label='Y = 1',color=Ycol,alpha=1,hjust=0,angle=90)
                        ,data.frame(y=ynote,x=-max(filter(dt,y=='n')$count)
                                    ,label='Y = 0',color=Ncol,alpha=1,hjust=0,angle=90)
             )
            
            dtY = filter(dt,y=='y')
            dtN = filter(dt,y=='n')
            
             p=ggplot(data=dt,aes(y=col,fill=col)) +
               ggplot2::geom_col(data=dtY,aes(x=count),fill='#2b8cbe')+
               ggplot2::geom_text(data=dtY,aes(x=1,label=label),size=3,hjust=-.5)+
               ggplot2::geom_col(data=dtN,aes(x=-count),fill='#a6bddb') +
               ggplot2::geom_text(data=dtN,aes(x=-1,label=label),size=3,hjust=1.5,alpha=0.7)+
               ggplot2::geom_text(data=note,aes(x=x,y=y,label=label,alpha=alpha,hjust=hjust,angle=angle)
                                  ,inherit.aes = F,size=5) +
               ggplot2::ggtitle(paste0('Y=0 vs. Y=1 for column ', col)) +
                ggplot2::theme(text = element_text(size=10)
                              ,axis.text.x = element_text(angle=90,size=10)
                              ,legend.position = "none")
               #ggplot2::scale_fill_brewer('blues')
               
           }
           
)
cowplot::plot_grid(plotlist = p,nrow = 2,ncol =2 , label_size=2)

```


# Data Cleaning

```{r}
# Removing Nas
data = dataRaw[-NAsRows,] %>%
  select(-c(x6,x41))
```

# Model XGBoost

```{r}

seed=1701
message(rep('=',30))
message('Processing Model: XGB, Name:')
message(rep('=',30))
#trainIndex <- createDataPartition(data$y, p = .8, list = FALSE, times = 1)
#dataTrain = data[trainIndex,]
#dataTest =  data[-trainIndex,]
# sampling

# sample= 0.1
```

